### ISSUE TITLE
Definition of Entry Types 

### ISSUE THREAD

**Issue by jnweiger** [restic/calens#4]
Calens uses
```
var EntryTypePriority = map[string]int{
	"Security":    1,
	"Bugfix":      2,
	"Change":      3,
	"Enhancement": 4,
}
```
That is a decent choice in my opinion. Nevertheless https://keepachangelog.com/en/1.0.0/#how
has a slightly different list of "Added", "Changed", "Deprecated", "Removed", "Fixed", and "Security"

I'd like to point users to an "authorative" source how to write good changelogs. keepachangelog.com is a prominent one -- do you recommend alternatives?

**Comment by rawtaz** [comment]
Any example of a (reasonably sized, e.g. for some restic release) changelog would be a good example of how to write a good, nice looking and easily digested changelog.

I'd say this is more important than the source of the information being authoritative.

**Comment by fd0** [comment]
I think the issue types we have are good. So there's nothing else to do in this issue, I'm therefore closing it. Please feel free to add further comments, thanks!
